<link rel="stylesheet" href="styles/8.1.Header.css">
<header>
    <h2 class="logo">jQuery</h2>
    <nav class="menu">
        <a href="1.1.Index.php">Home</a>
        <a href="2.1.Topic_1.php">Topic</a>
        <a href="4.1.Quiz.php">Quiz</a>
        <a href="5.1.Enhancements.php">HTML Enhancements</a>
        <a href="5.2.PHPEnhansment.php">PHP Enhancements</a>
        <a href="6.1.About_Us.php">About Us</a>
        <a href="7.1.Manage_Entrance.php">Manage</a>
    </nav>
</header>